name: Auto Update Free Games

on:
  schedule:
    # - cron: "0 */6 * * *"  # For Testing: every 6 hours
    - cron: "0 23 * * 4"  # For Final: every day at midnight UTC
  workflow_dispatch:

jobs:
  update-games:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_1: ${{ secrets.DISCORD_WEBHOOK_1 }}
      DISCORD_WEBHOOK_2: ${{ secrets.DISCORD_WEBHOOK_2 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md games.json
          git commit -m "Auto-update free games list" || echo "No changes to commit"
          git push
