name: Auto Update Free Games

on:
  schedule:
    - cron: '0 6 * * *'  
  workflow_dispatch:      
  push:
    branches:
      - main

jobs:
  update-games:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run scraper
        run: python scraper.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add games.json README.md
          git commit -m "🔄 Auto update free games list" || echo "No changes"
          git push
